config/routes.rb
Blog::Application.routes.draw do
  resources :tags
  resources :articles do
    get :preview, on: :member
  end

  root "page#homepage"

  namespace :admin do
    resources :tags
    resources :articles
  end

  # api
  get 'subtitle' => "page#change_subtitle"
  get 'ab_test' => 'page#ab_test'
  get 'mortal' => 'page#mortal'
  get "cv" => "page#cv"

  # static
  get "cv-en" => "page#CV_en"

  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  # errors
  match '*', via: :all, to:'page#error_404'
end

app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_paranoid
	self.per_page = 1

	belongs_to :tag

	scope :published, -> { where( publish_switch:true) }

  # Not fit so well with old test
  # searchable do
  #   text :title
  # end

	def previous_article
    get_article(true,self.id)
	end

	def next_article
		get_article(false,self.id)
	end

	def published?
		self.publish_switch
	end

	private
	# Set max time for search article
	def get_article(direction, article_id)
    current_id = get_current_id(direction, article_id)
    begin
      article = Article.find(current_id)
      raise 'Current article not published error' unless article.published?
    rescue
    	article = get_article(direction, current_id)
    end
    article
	end

  def get_current_id( direction, article_id)
    start_id = Article.first.id
    end_id = Article.last.id
    id = direction ? article_id -1 : article_id + 1
    
    case id
    when (start_id - 1) then
      id = end_id
    when (end_id + 1) then
      id = start_id
    else
    end
    id
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	acts_as_paranoid
  
	has_many :articles

  def self.article_published
    all.to_a.delete_if{|tag| tag.articles.published.count < 1 }
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	def index
		
	end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  http_basic_authenticate_with name:'admin', password:'realwol', except:[:show]

  def index
    @tags = Tag.all
    respond_to do |format|
      format.html
      format.json { render :json => @tags }
      format.text { render :text => @tags }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method [:mark_down]

  # Highlight code with Pygments
  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = "ruby" if language.blank?
      # Fix first line missing table
      # Ps: only in development, OK with production mode
      code = code.insert(0,"    ") unless Rails.env.production?
      # Fix last line odd enter line
      code.chomp!
      CodeRay.scan(code, language).div(:tab_width=>2)
    end
  end

  protected
  def mark_down(text)
    options = {
      :autolink => true,
      :no_intra_emphasis => true,
      # :fenced_code_blocks => true,
      :lax_html_blocks => true,
      :strikethrough => true,
      :superscript => true,
      :tables => true,
      :hightlights => true
    }
	  Redcarpet::Markdown.new(HTMLwithCoderay, options).render(text).html_safe
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name:'admin', password:'realwol', except:[:show]

  def index
    page = params[:page] || 1
    @articles = Article.published.order("publish_switch desc").paginate(page: params[:page])
    respond_to do |format|
      format.html
      format.json { render :json => @articles }
      format.text { render :text => @articles }
    end
  end

  def show
    if @article.published?
      respond_to do |format|
        format.html
        format.json { render :json => @article }
        format.text { render :text => @article }
      end
    else
      redirect_to articles_path
    end
  end

  def preview
    @article = Article.find(params[:id])
    render 'show'
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      begin
        @article = Article.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render file: "#{Rails.root}/public/404.html", status:404, layout:false
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :tag_id, :publish_switch)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def homepage
    EmailWorker.perform_async if params[:email]
  end

  def mortal
    render layout:'mortal'
  end

  def change_subtitle
    if params[:sub_title]
  	  session[:sub_title] = '=>' + params[:sub_title]
    end
  	redirect_to root_path
  end

  def ab_test
    # sleep 0.1
    render text: Article.published
  end

  def cv
    render layout:'mortal'
    # render file: "#{Rails.root}/public/cv.html", layout:default
  end

  def CV_en
  	render file: "#{Rails.root}/public/cv-en.html", layout:default
  end

  def error_404
  	render file: "#{Rails.root}/public/404.html", status:404, layout:false
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    headers['Access-Control-Allow-Origin'] = '*'
    request.format = :json
    @tags = Tag.all
    respond_to do |format|
      format.html
      format.json { render :json => @tags }
    end
  end

  def show
    if @tag
      @articles = @tag.articles.published
    end
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	require 'constant'

	def admin?
		
	end

	def cv_out?
		CV_OUT
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/admin/articles/index.html.haml
all articles here

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :style=>"height:25px; width:500px" %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, rows:50, cols:150 %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.collection_select :tag_id, Tag.all, "id", "name"%>
  </div>
  <div class="field">
    <%= f.label :publish_switch %>
    <%= f.check_box :publish_switch %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Published</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.published? %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'preview', preview_article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= will_paginate @articles %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.haml
.turn_page_button
  =render 'partials/article/page_turn_button'
.article_area
  %h1
    =@article.title

  -if @article.tag
    = '-'+ @article.tag.name 
  -else
    = '- Others'
  %p{style:'font-size:12px;'}
    / －文章中在某些突兀的地方出现的“（1） （2）”这类字符是笔者觉得需要做些许解释地方，解释内容将会在文章结尾以此给出，特标记，无任何语义且会缺省，乱序。
  %hr
  %p
    -a = Time.now
    -cache(@article, expires_in: 10.minutes) do
      =mark_down @article.content
    = Time.now - a if params[:t]
.link_area

:css
  .article_area{
    border-style:outset;
    border-width: 1px;
    margin-left:15%;
    margin-right:15%;
    padding: 10px;
  }

  .link_area{
    text-align: right;
    margin-right:5%;
  }

  p{
    font-size:14px;
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    =stylesheet_link_tag 'application', media:'all', 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags
    =favicon_link_tag 'favicon.ico'
  =render 'partials/homepage/header'
  =yield
  =cache 'footer', expires_in: 1.minutes do
    =render 'partials/homepage/footer'

app/views/layouts/mortal.html.haml
!!!
%html
  %head
    %title Blog
    =stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track"=> true
    =stylesheet_link_tag 'css/bootstrap.min'
    =stylesheet_link_tag 'buttons'
    =stylesheet_link_tag 'main'
    =stylesheet_link_tag 'css/bootstrap-responsive.min'
    =javascript_include_tag 'application', "data-trubolinks-track"=> true
    =javascript_include_tag 'js/bootstrap.min'
    =javascript_include_tag 'buttons'
    =csrf_meta_tags
    =favicon_link_tag 'favicon.ico'
  %body{style:"padding: 0 0 0; margin-top:-10px;"}
    =yield

app/views/page/homepage.html.haml
=render_cell(:homepage, :article_list)

app/views/page/mortal.html.haml
.header{style:"background:url('"+asset_path("head.jpg")+"'); height:400px;margin-top:0px;"}
  %h1{style:'text-align:center; padding-top:150px;'}
    I love
    %font{style:'font-size:70px;'}
      Ruby
    and
    %font{style:'font-size:70px;'}
      Rails.
  %h1{style:'text-align:center; margin-top:50px; margin-left:150px;'}
    I need a
    %font{style:'font-size:70px;'}
      Job
    now!
.self_intro{style:'height:400px;text-align:center;'}
  / %h2
  /   %span.label.label-primary{style:"background-color:#CBA578; padding:10px 12px;"}
  /     %font{style:"font-size:20px;"}
  /       自我介绍
  .intro_content{style:"text-align:left;width:80%; margin-left:10%; margin-top:50px;"}
    %table
      %tr
        %td
          &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
        %td.pad_td
          从事Ruby on Rails三年有余，喜欢
        %td
          .thumbnial.round_pic{style:"background:url('"+asset_path("cl.jpg")+"');"}
        %td.pad_td
          崇拜
        %td
          .thumbnial.round_pic{style:"background:url('"+asset_path("rocket.jpg")+"');"}
        %td.pad_td
          佩服
        %td
          .thumbnial.round_pic{style:"background:url('"+asset_path("dhh.jpg")+"');"}
    .hobbit{style:"color:rgb(85, 85, 85);"}
      %h2{style:"text-align:center"}
      %h2{style:"text-align:center; margin-top:50px;"}
        %font{style:"font-size:18px"}
          大学加入
        校足球队
      %h2{style:"text-align:center;"}
        %font{style:"font-size:18px"}
          有属于自己的
        球杆
      %h2{style:"text-align:center"}
        %font{style:"font-size:18px"}
          也在拜读
        Rails
        %font{style:"font-size:18px;"}
          的
        源代码
.project_exp{style:'text-align:center;'}
  %hr
  %table{style:"width:80%; margin-left:10%;"}
    %tr{style:"background-color:"}
      %td{}
        =image_tag('rails.jpg',style:"width:130px;")
      %td{colspan:"3"}
        %p{style:"font-size:14px;text-align:left;"}
          &nbsp&nbsp&nbsp&nbsp使用Ruby on Rails到现在三年有余，理解 MCV 和 Convention Over Configuration，欣赏gem来定制自己想要的东西的方式，感谢rake，rack和middleware做的所有，也赞叹ActiveRecord，ActionPack，ActiveSupport美妙的实现方式。当然大大小小的坑也是踩了无数。强忍着阅读Rails源代码的过程中，着实收获颇丰。而且个人的笔记也记录在blog中，希望能帮助到自己和其他人。
    %tr{style:"margin-top:10px;"}
      %td{style:"width:130px;"}
        =image_tag('ruby.jpg',style:"width:110px; height:130px;")
      %td{colspan:"3"}
        %p{style:"font-size:14px;text-align:left;"}
          &nbsp&nbsp&nbsp&nbsp跟多数人的顺序一样，先Rails后Ruby；不过俗话说得好，好饭不怕晚。接触Ruby不久之后，就慕名前去阅读《Ruby元编程》，终于在七八遍之后，对其中的知识也可以在自己的项目中运用了。接下来在不断阅读开源代码的过程中，也陆陆续续的读了好几篇ruby的入门教材，去重选精的读，收获很大。接下来读到《松本行弘的程序世界》，好像又回到几年前刚读元编程时候的感觉了。不过看来看去还是有很多视野上的突破和拓展。随后又做一些小程序来拓展比如：leetcode，在正与人同时开发中，收获也不小。
    %tr{style:"margin-top:10px;"}
      %td{style:"width:130px;"}
        %p{style:"font-size:50px;margin-top:50px;"}
          TDD
      %td{colspan:"3"}
        %p{style:"font-size:14px;margin-top:50px;text-align:left;"}
          &nbsp&nbsp&nbsp&nbsp打算把TDD单独提出来说还是要归结在一本书上：《Ruby Best Practices》。之前总是被强调TDD，总是听说，项目中也写测试，不过多数是之后再去补的。不过自从阅读了这本书关于测试的部分之后，按照书中的来了一遍，写代码错别字少了，bug也没了，连新需求都变的简单了。所以在接下来的开发中，时间集中在如何设计方法和测试用例上了，感觉真的有了提升，我多说也无益，不明白的朋友自己阅读感受一下就知道了。
    %tr
      %td{colspan:"5"}
        %hr
    %tr{style:"padding-top:20px;height:50px;"}
      %td{colspan:'4', style:"font-size:25px;"}
        有项目经验的技术
    %tr
      %td{colspan:"5"}
        %br
    %tr
      %td
        =image_tag('nginx.jpg', alt:'nginx', style:"width:170px;")
      %td
        =image_tag('mina.png', style:"width:170px;")
      %td
        =image_tag('thin.jpg', style:"width:170px;")
      %td
        %p{style:"font-size:25px;padding-left:40px; font-weight:solid;"}
          UNICORN
    %tr
      %td
        =image_tag('angular.jpg', style:"width:170px;")
      %td
        =image_tag('ember.jpg', style:"width:170px;")
      %td
        =image_tag('git.jpg', style:"width:170px;")
      %td
        =image_tag('jquery.png', style:"width:170px;")
    %tr
      %td
        =image_tag('bootstrap.jpg', style:"width:170px;")
      %td
        =image_tag('mysql.jpg', style:"width:170px;")
      %td
        =image_tag('mongodb.png', style:"width:170px;")
      %td
        =image_tag('redis.png', style:"width:170px;")

.bottom_div{style:"height:300px;background:#2e3234;"}
  .logo_img{style:"margin-left:48%;"}
    =image_tag('favicon.ico', style:"height:100px; width:50px;margin-top:90px;")
  %p{style:"color:white;font-size:20px;text-align:center;"}
    =link_to 'Blog', "http://115.28.32.95"
    =link_to 'Email', "mailto:realwol@gamil.com"
    =link_to 'Github', "https://github.com/GaaraLi"
    =link_to 'Ruby-China', "https://ruby-china.org/realwol"

:css
  .round_pic{
    width:140px;
    height:140px;
    border-radius:30px;
    box-shadow: 2px 7px 10px 2px;
  }
  .pad_td{
    padding: 15px;
    padding-top: 100px;
  }

app/views/partials/article/_page_turn_button.html.haml
.left_turn_btn
  =link_to '<', article_path(@article.previous_article), style:'text-decoration:none;'
.right_turn_btn
  =link_to '>', article_path(@article.next_article), style:'text-decoration:none;'

:css
  .left_turn_btn{
    position: fixed;
    left: 20px;
    top: 50%;
    font-size:40px;
    cursor:pointer;
  }
  .right_turn_btn{
    position: fixed;
    right: 20px;
    top: 50%;
    font-size:40px;
    cursor:pointer;
  }

app/views/partials/homepage/_article_list.html.haml
.article_list_margin{style:'margin-left:20px;'}
  -if @articles.count > 0
    -@articles.each do |article|
      %h3
        =link_to article.title, article_path(article.id)
  -else
    本标签下无文章

app/views/partials/homepage/_footer.html.haml
%hr
  -Tag.article_published.each do |t|
    =link_to t.name, tag_path(t.id), style:"text-decoration:none;"

app/views/partials/homepage/_header.html.haml
%h2{ style:"margin-top:30px; margin-bottom:30px;"}
  =link_to 'Realwol', root_path
  =session[:sub_title]
.header_right{style:'text-align:right; float:right; margin-top:-20px;'}
  =link_to 'Want color ?', mortal_path unless Rails.env.production?
%hr

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.haml
=render 'partials/homepage/article_list', locals:{articles: @articles}